/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetapp4nathanlazarowicz;

import java.awt.event.KeyEvent;
import java.util.Arrays;
import java.util.HashSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lazarowicz
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        //Initialisation GET :
        
        initialisation();
        //code 
        
        
    }
    
    //Méthodes :
    
    /**
     * Permet d'initiliser les affichages de l'interface. 
     * 
     */
    public void initialisation(){
        //Planning
        Planning planning = new Planning("initialisation", "init");
        labelLundiSeance.setText(planning.getNomSeancePlanning("lundi"));
        labelMardiSeance.setText(planning.getNomSeancePlanning("mardi"));
        labelMercrediSeance.setText(planning.getNomSeancePlanning("mercredi"));
        labelJeudiSeance.setText(planning.getNomSeancePlanning("jeudi"));
        labelVendrediSeance.setText(planning.getNomSeancePlanning("vendredi"));
        labelSamediSeance.setText(planning.getNomSeancePlanning("samedi"));
        labelDimancheSeance.setText(planning.getNomSeancePlanning("dimanche"));
        
        //Exercice
        
        Exercice exercice = new Exercice("init", "initialisation", "initialisation", "initialisation");
        int ligneExercice = exercice.getNombreLigneExercice();
        //tableExercice.addRow(new Object[]{nomExo, typeExo, grpMuscu, muscle});
        for(int i = 0; i < ligneExercice; i++){
            String[] exerciceData = exercice.lectureDonneesExercice(i+1);
            DefaultTableModel model = (DefaultTableModel) tableExercice.getModel();
            model.addRow(new Object[]{exerciceData[0], exerciceData[1], exerciceData[2], exerciceData[3]});
            /*
            tableExercice.getModel().setValueAt(exerciceData[0], i, 0);
            //System.out.println("Exercice " + i + " = " + exerciceData[0]);
            tableExercice.getModel().setValueAt(exerciceData[1], i, 1);
            tableExercice.getModel().setValueAt(exerciceData[2], i, 2);
            tableExercice.getModel().setValueAt(exerciceData[3], i, 3);
            */
        }
        
        //Seance 
        Seance seance = new Seance("init","initialisation","initialisation");
        int ligneSeance = seance.getNombreLigneSeance();
        for(int i = 0; i < ligneSeance; i++){
            String[] seanceData = seance.lectureDonneesSeance(i+1);
            DefaultTableModel model = (DefaultTableModel) tableSeance.getModel();
            model.addRow(new Object[]{
                    seanceData[0], seanceData[1], seanceData[2], seanceData[3],
                    seanceData[4], seanceData[5], seanceData[6], seanceData[7],
                    seanceData[8], seanceData[9], seanceData[10], seanceData[11]
                    });
        }  
        
        //Musculation
        Musculation muscu = new Musculation("init","initialisation","initialisation", "initialisation");
        int ligneMuscu = muscu.getNombreLigneMusculation();
        for(int i = 0; i < ligneMuscu; i++){
            String[] muscuData = muscu.lectureDonneesMusculation(i+1);
            DefaultTableModel model = (DefaultTableModel) tableMusculation.getModel();
            model.addRow(new Object[]{
                    muscuData[0], muscuData[1], muscuData[2], muscuData[3],
                    muscuData[4], muscuData[5] });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Planning = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        bpSupprimer = new javax.swing.JButton();
        bpModifier = new javax.swing.JButton();
        txtJourSeance = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNomSeance = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelLundi = new javax.swing.JLabel();
        labelLundiSeance = new javax.swing.JLabel();
        labelMardiSeance = new javax.swing.JLabel();
        labelMardi = new javax.swing.JLabel();
        labelMercredi = new javax.swing.JLabel();
        labelMercrediSeance = new javax.swing.JLabel();
        labelJeudi = new javax.swing.JLabel();
        labelJeudiSeance = new javax.swing.JLabel();
        labelVendredi = new javax.swing.JLabel();
        labelVendrediSeance = new javax.swing.JLabel();
        labelSamedi = new javax.swing.JLabel();
        labelSamediSeance = new javax.swing.JLabel();
        labelDimanche = new javax.swing.JLabel();
        labelDimancheSeance = new javax.swing.JLabel();
        Séances = new javax.swing.JPanel();
        txtExercice2 = new javax.swing.JComboBox<>();
        labelNombreExercice = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSeance = new javax.swing.JTable();
        bpAjouterSeance = new javax.swing.JButton();
        txtNomSeance2 = new javax.swing.JTextField();
        bpSupprimerSeance = new javax.swing.JButton();
        bpSupprimerExercice2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtRechercheSeance = new javax.swing.JTextField();
        txtTypeSeance = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtRechercheNumeroExercice = new javax.swing.JTextField();
        Musculation = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableMusculation = new javax.swing.JTable();
        txtExercice3 = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JFormattedTextField();
        txtHeure = new javax.swing.JFormattedTextField();
        txtSerie = new javax.swing.JTextField();
        txtRepetition = new javax.swing.JTextField();
        txtPoids = new javax.swing.JTextField();
        bpAjouterMusculation = new javax.swing.JButton();
        Exercices = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNomExercice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTypeExercice = new javax.swing.JComboBox<>();
        txtGrpMuscu = new javax.swing.JComboBox<>();
        txtMuscle = new javax.swing.JComboBox<>();
        bpAjouterExercice = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtRechercheExercice = new javax.swing.JTextField();
        bpSupprimerExercice = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableExercice = new javax.swing.JTable();
        Options = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        bpNewDataBase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 410));
        setSize(new java.awt.Dimension(800, 420));

        jTabbedPane1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(800, 400));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        Planning.setAlignmentX(0.0F);
        Planning.setAlignmentY(0.0F);

        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bpSupprimer.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bpSupprimer.setText("Supprimer");
        bpSupprimer.setPreferredSize(new java.awt.Dimension(200, 70));
        bpSupprimer.setSize(new java.awt.Dimension(100, 23));
        bpSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpSupprimerActionPerformed(evt);
            }
        });

        bpModifier.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bpModifier.setText("Modifier");
        bpModifier.setPreferredSize(new java.awt.Dimension(200, 70));
        bpModifier.setSize(new java.awt.Dimension(100, 23));
        bpModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bpModifierMouseClicked(evt);
            }
        });
        bpModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpModifierActionPerformed(evt);
            }
        });

        txtJourSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtJourSeance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche" }));
        txtJourSeance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJourSeanceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Sélectionnez votre jour et entrez le nom de votre sénace");

        txtNomSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtNomSeance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nom de votre séance"}));
        txtNomSeance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomSeanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bpSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtJourSeance, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomSeance, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bpModifier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJourSeance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomSeance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(bpModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bpSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Jours");

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel8.setText("Séances");

        labelLundi.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelLundi.setText("Lundi :");

        labelLundiSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelLundiSeance.setText("Rien de prévu");

        labelMardiSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelMardiSeance.setText("Rien de prévu");

        labelMardi.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelMardi.setText("Mardi :");

        labelMercredi.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelMercredi.setText("Mercredi :");

        labelMercrediSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelMercrediSeance.setText("Rien de prévu");

        labelJeudi.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelJeudi.setText("Jeudi :");

        labelJeudiSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelJeudiSeance.setText("Rien de prévu");

        labelVendredi.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelVendredi.setText("Vendredi :");

        labelVendrediSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelVendrediSeance.setText("Rien de prévu");

        labelSamedi.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelSamedi.setText("Samedi :");

        labelSamediSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelSamediSeance.setText("Rien de prévu");

        labelDimanche.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelDimanche.setText("Dimanche :");

        labelDimancheSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelDimancheSeance.setText("Rien de prévu");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelLundi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelSamedi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelDimanche, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelVendredi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelMercredi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelJeudi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelMardi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelSamediSeance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDimancheSeance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelVendrediSeance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelLundiSeance, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMercrediSeance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelJeudiSeance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMardiSeance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLundi)
                    .addComponent(labelLundiSeance))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMardi)
                    .addComponent(labelMardiSeance))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMercredi)
                    .addComponent(labelMercrediSeance))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJeudi)
                    .addComponent(labelJeudiSeance))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVendredi)
                    .addComponent(labelVendrediSeance))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSamedi)
                    .addComponent(labelSamediSeance))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDimanche)
                    .addComponent(labelDimancheSeance))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PlanningLayout = new javax.swing.GroupLayout(Planning);
        Planning.setLayout(PlanningLayout);
        PlanningLayout.setHorizontalGroup(
            PlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlanningLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PlanningLayout.setVerticalGroup(
            PlanningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Planning", Planning);

        txtExercice2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtExercice2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Exercices"}));
        txtExercice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExercice2ActionPerformed(evt);
            }
        });

        labelNombreExercice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelNombreExercice.setText("0");

        tableSeance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom séance", "Type", "Exercice 1", "Exercice 2", "Exercice 3", "Exercice 4","Exercice 5", "Exercice 6", "Exercice 7", "Exercice 8", "Exercice 9","Exercice 10"
            }
        ));
        jScrollPane2.setViewportView(tableSeance);
        tableSeance.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        bpAjouterSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bpAjouterSeance.setText("Ajouter");
        bpAjouterSeance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpAjouterSeanceActionPerformed(evt);
            }
        });

        txtNomSeance2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtNomSeance2.setText("Nom de votre séance");
        txtNomSeance2.setMinimumSize(new java.awt.Dimension(189, 29));
        txtNomSeance2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomSeance2MouseClicked(evt);
            }
        });
        txtNomSeance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomSeance2ActionPerformed(evt);
            }
        });
        txtNomSeance2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomSeance2KeyPressed(evt);
            }
        });

        bpSupprimerSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bpSupprimerSeance.setText("Supprimer séance");
        bpSupprimerSeance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpSupprimerSeanceActionPerformed(evt);
            }
        });

        bpSupprimerExercice2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bpSupprimerExercice2.setText("Supprimer exercice");
        bpSupprimerExercice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpSupprimerExercice2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel9.setText("Recherche :");

        txtRechercheSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtRechercheSeance.setText("Nom séance");
        txtRechercheSeance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRechercheSeanceMouseClicked(evt);
            }
        });
        txtRechercheSeance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRechercheSeanceActionPerformed(evt);
            }
        });
        txtRechercheSeance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRechercheSeanceKeyPressed(evt);
            }
        });

        txtTypeSeance.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtTypeSeance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Musculation", "Endurance", "Conditionnement" }));
        txtTypeSeance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeSeanceActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel10.setText("Exercice n° :");

        txtRechercheNumeroExercice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtRechercheNumeroExercice.setText("N");
        txtRechercheNumeroExercice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRechercheNumeroExerciceMouseClicked(evt);
            }
        });
        txtRechercheNumeroExercice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRechercheNumeroExerciceActionPerformed(evt);
            }
        });
        txtRechercheNumeroExercice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRechercheNumeroExerciceKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout SéancesLayout = new javax.swing.GroupLayout(Séances);
        Séances.setLayout(SéancesLayout);
        SéancesLayout.setHorizontalGroup(
            SéancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SéancesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SéancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SéancesLayout.createSequentialGroup()
                        .addComponent(txtNomSeance2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTypeSeance, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SéancesLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SéancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(SéancesLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRechercheNumeroExercice))
                            .addComponent(txtRechercheSeance, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(SéancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SéancesLayout.createSequentialGroup()
                        .addComponent(txtExercice2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNombreExercice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bpAjouterSeance, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SéancesLayout.createSequentialGroup()
                        .addGroup(SéancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bpSupprimerExercice2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bpSupprimerSeance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(SéancesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SéancesLayout.setVerticalGroup(
            SéancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SéancesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(SéancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomSeance2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExercice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreExercice)
                    .addComponent(txtTypeSeance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpAjouterSeance))
                .addGap(21, 21, 21)
                .addGroup(SéancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtRechercheSeance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpSupprimerSeance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SéancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SéancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtRechercheNumeroExercice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bpSupprimerExercice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Séances", Séances);

        tableMusculation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exercices", "Date", "Heure", "Série", "Répétition", "Poids"
            }
        ));
        jScrollPane3.setViewportView(tableMusculation);
        tableMusculation.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        txtExercice3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtExercice3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Exercice"}));
        txtExercice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExercice3ActionPerformed(evt);
            }
        });

        txtDate.setColumns(3);
        txtDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtDate.setToolTipText("");
        txtDate.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });

        txtHeure.setColumns(3);
        txtHeure.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));
        txtHeure.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtHeure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeureActionPerformed(evt);
            }
        });

        txtSerie.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtSerie.setText("Séries");
        txtSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerieActionPerformed(evt);
            }
        });

        txtRepetition.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtRepetition.setText("Répétitions");
        txtRepetition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepetitionActionPerformed(evt);
            }
        });

        txtPoids.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtPoids.setText("Poids");
        txtPoids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPoidsActionPerformed(evt);
            }
        });
        txtPoids.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPoidsKeyPressed(evt);
            }
        });

        bpAjouterMusculation.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bpAjouterMusculation.setText("Ajouter");
        bpAjouterMusculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpAjouterMusculationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MusculationLayout = new javax.swing.GroupLayout(Musculation);
        Musculation.setLayout(MusculationLayout);
        MusculationLayout.setHorizontalGroup(
            MusculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(MusculationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtExercice3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtHeure, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MusculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MusculationLayout.createSequentialGroup()
                        .addComponent(txtRepetition, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPoids, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bpAjouterMusculation, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MusculationLayout.setVerticalGroup(
            MusculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MusculationLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(MusculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MusculationLayout.createSequentialGroup()
                        .addGroup(MusculationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                            .addComponent(txtDate)
                            .addComponent(txtHeure)
                            .addComponent(txtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRepetition, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPoids, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MusculationLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtExercice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bpAjouterMusculation)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Musculation", Musculation);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("Exercice :");

        txtNomExercice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtNomExercice.setText("Nom exercice");
        txtNomExercice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomExerciceMouseClicked(evt);
            }
        });
        txtNomExercice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomExerciceActionPerformed(evt);
            }
        });
        txtNomExercice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomExerciceKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel4.setText("Type :");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel5.setText("Groupement Musculaire :");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel6.setText("Muscles");

        txtTypeExercice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtTypeExercice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Musculation", "Endurance", "Conditionnement" }));
        txtTypeExercice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeExerciceActionPerformed(evt);
            }
        });

        txtGrpMuscu.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtGrpMuscu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jambes", "Bras", "Dos", "Pectoraux", "Epaules"}));
        txtGrpMuscu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrpMuscuActionPerformed(evt);
            }
        });

        txtMuscle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtMuscle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        txtMuscle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMuscleActionPerformed(evt);
            }
        });

        bpAjouterExercice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bpAjouterExercice.setText("Ajouter");
        bpAjouterExercice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpAjouterExerciceActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel7.setText("Recherche :");

        txtRechercheExercice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        txtRechercheExercice.setText("Nom exercice");
        txtRechercheExercice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRechercheExerciceMouseClicked(evt);
            }
        });
        txtRechercheExercice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRechercheExerciceActionPerformed(evt);
            }
        });
        txtRechercheExercice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRechercheExerciceKeyPressed(evt);
            }
        });

        bpSupprimerExercice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bpSupprimerExercice.setText("Supprimer");
        bpSupprimerExercice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpSupprimerExerciceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(138, 138, 138)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTypeExercice, 0, 1, Short.MAX_VALUE)
                                    .addComponent(txtNomExercice, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtGrpMuscu, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMuscle, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRechercheExercice))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bpAjouterExercice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bpSupprimerExercice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomExercice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTypeExercice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGrpMuscu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMuscle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bpAjouterExercice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtRechercheExercice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bpSupprimerExercice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tableExercice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Exercices", "Types", "Groupement musculaire", "Muscles"
            }
        ));
        tableExercice.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tableExercice);
        tableExercice.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout ExercicesLayout = new javax.swing.GroupLayout(Exercices);
        Exercices.setLayout(ExercicesLayout);
        ExercicesLayout.setHorizontalGroup(
            ExercicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExercicesLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE))
        );
        ExercicesLayout.setVerticalGroup(
            ExercicesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExercicesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Exercices", Exercices);

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bpNewDataBase.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        bpNewDataBase.setText("Nouveau fichier");
        bpNewDataBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpNewDataBaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OptionsLayout = new javax.swing.GroupLayout(Options);
        Options.setLayout(OptionsLayout);
        OptionsLayout.setHorizontalGroup(
            OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bpNewDataBase, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(596, Short.MAX_VALUE))
        );
        OptionsLayout.setVerticalGroup(
            OptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OptionsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(bpNewDataBase)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Options", Options);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(800, 428));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    //Planning
    private void txtJourSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJourSeanceActionPerformed
        // TODO add your handling code here:
        Seance seance = new Seance("init","","");
        int seanceMax  = seance.getSeanceMax();
        String[] dataSeance = new String[seanceMax];
        
        for(int i = 1; i <= seanceMax; i++){
            dataSeance[i-1] = seance.getNomSeance(i);
        }
        
        Arrays.sort(dataSeance, String.CASE_INSENSITIVE_ORDER);
        
        DefaultComboBoxModel model = (DefaultComboBoxModel) txtNomSeance.getModel();
        
        model.removeAllElements();
        for (String seanceData : dataSeance) {
            model.addElement(seanceData);
        }
    }//GEN-LAST:event_txtJourSeanceActionPerformed

    //EXERCICE
    private void txtTypeExerciceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeExerciceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeExerciceActionPerformed

    private void txtNomExerciceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomExerciceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomExerciceActionPerformed

    private void txtMuscleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMuscleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMuscleActionPerformed

    private void bpAjouterExerciceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpAjouterExerciceActionPerformed
        // TODO add your handling code here:
        String nomExo = txtNomExercice.getText();
        String typeExo = (String)txtTypeExercice.getSelectedItem();
        String grpMuscu = (String)txtGrpMuscu.getSelectedItem();
        String muscle = (String)txtMuscle.getSelectedItem();
        
        Exercice exercice = new Exercice(nomExo, typeExo, grpMuscu, muscle);
        //int ligne = exercice.getNombreLigneExercice();
        //tableExercice.getModel().addRow(new Object[]{nomExo, typeExo, grpMuscu, muscle});
        DefaultTableModel model = (DefaultTableModel) tableExercice.getModel();
        model.addRow(new Object[]{nomExo, typeExo, grpMuscu, muscle});
        
        /*
        tableExercice.getModel().setValueAt(nomExo, ligne - 1, 0);
        tableExercice.getModel().setValueAt(typeExo, ligne - 1, 1);
        tableExercice.getModel().setValueAt(grpMuscu, ligne - 1, 2);
        tableExercice.getModel().setValueAt(muscle, ligne - 1, 3);
        */
        
        txtNomExercice.setText("");
        
    }//GEN-LAST:event_bpAjouterExerciceActionPerformed

    private void bpSupprimerExerciceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpSupprimerExerciceActionPerformed
        // TODO add your handling code here:
        String recherche = txtRechercheExercice.getText();
        Exercice exercice = new Exercice("init", "", "", "");
        int ligne = exercice.getNombreLigneExercice();

        exercice.removeExercice(recherche);
        ligne --;
        for(int i = 0; i <= ligne; i++){
            String[] exerciceData = exercice.lectureDonneesExercice(i+1);
            //DefaultTableModel model = (DefaultTableModel) tableExercice.getModel();
            //model.addRow(new Object[]{exerciceData[0], exerciceData[1], exerciceData[2], exerciceData[3]});
            tableExercice.getModel().setValueAt(exerciceData[0], i, 0);
            tableExercice.getModel().setValueAt(exerciceData[1], i, 1);
            tableExercice.getModel().setValueAt(exerciceData[2], i, 2);
            tableExercice.getModel().setValueAt(exerciceData[3], i, 3);
            
        }
        DefaultTableModel model = (DefaultTableModel) tableSeance.getModel();
        model.removeRow(ligne);
        /*
        tableExercice.getModel().setValueAt(null, ligne, 0);
        tableExercice.getModel().setValueAt(null, ligne, 1);
        tableExercice.getModel().setValueAt(null, ligne, 2);
        tableExercice.getModel().setValueAt(null, ligne, 3);
        */
        //DefaultTableModel model = (DefaultTableModel) tableExercice.getModel();
        //model.removeRow(ligne);
        
        txtRechercheExercice.setText(null);
    }//GEN-LAST:event_bpSupprimerExerciceActionPerformed

    private void txtRechercheExerciceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRechercheExerciceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechercheExerciceActionPerformed

    private void bpModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bpModifierMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bpModifierMouseClicked

    
    //PLANNING SUITE :
    private void bpModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpModifierActionPerformed
        // TODO add your handling code here:
        String jourSeance = (String)txtJourSeance.getSelectedItem();
        String nomSeance = (String)txtNomSeance.getSelectedItem();
        
        Planning planning = new Planning(nomSeance, jourSeance);
        
        switch(jourSeance){
            case "Lundi" : labelLundiSeance.setText(nomSeance); break;
            case "Mardi" : labelMardiSeance.setText(nomSeance); break;
            case "Mercredi" : labelMercrediSeance.setText(nomSeance); break;
            case "Jeudi" : labelJeudiSeance.setText(nomSeance); break;
            case "Vendredi" : labelVendrediSeance.setText(nomSeance); break;
            case "Samedi" : labelSamediSeance.setText(nomSeance); break;
            case "Dimanche" : labelDimancheSeance.setText(nomSeance); break;
        }
    }//GEN-LAST:event_bpModifierActionPerformed

    private void bpSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpSupprimerActionPerformed
        // TODO add your handling code here:
        String jourSeance = (String)txtJourSeance.getSelectedItem();
        
        Planning planning = new Planning("", jourSeance);
        
        switch(jourSeance){
            case "Lundi" : labelLundiSeance.setText(null); break;
            case "Mardi" : labelMardiSeance.setText(null); break;
            case "Mercredi" : labelMercrediSeance.setText(null); break;
            case "Jeudi" : labelJeudiSeance.setText(null); break;
            case "Vendredi" : labelVendrediSeance.setText(null); break;
            case "Samedi" : labelSamediSeance.setText(null); break;
            case "Dimanche" : labelDimancheSeance.setText(null); break;
        }
    }//GEN-LAST:event_bpSupprimerActionPerformed

    //EXERCICE
    private void txtNomExerciceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomExerciceMouseClicked
        // TODO add your handling code here:
        txtNomExercice.setText(null);
    }//GEN-LAST:event_txtNomExerciceMouseClicked

    
    //Options :
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Excel reset = new Excel("baseDeDonnee"); 
        reset.creerFichierExcel("baseDeDonnee");
        initialisation();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    //EXERCICE SUITE
    private void txtRechercheExerciceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRechercheExerciceMouseClicked
        // TODO add your handling code here:
        txtRechercheExercice.setText(null);
    }//GEN-LAST:event_txtRechercheExerciceMouseClicked

    private void txtNomExerciceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomExerciceKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bpAjouterExerciceActionPerformed(null);
        }
    }//GEN-LAST:event_txtNomExerciceKeyPressed

    //Exercice
    private void txtGrpMuscuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrpMuscuActionPerformed
        // TODO add your handling code here:
        final String[] J = {"Quadriceps", "Mollet", "ischio", "Adducteur", "Fessier"};
        final String[] B = {"Biceps", "Triceps", "Avant bras"};
        final String[] D = {"Trapèze", "Grand dorsale", "Lombaire"};
        final String[] P = {"Haut", "Bas"};
        final String[] E = {"Antérieur", "Latérale", "Postérieur"};
    
        DefaultComboBoxModel model = (DefaultComboBoxModel) txtMuscle.getModel();

        String grpM = (String) txtGrpMuscu.getSelectedItem();
        switch (grpM) {
            case "Jambes":
                model.removeAllElements();
                for (String muscle : J) {
                    model.addElement(muscle);
                }
                break;
            case "Bras":
                model.removeAllElements();
                for (String muscle : B) {
                    model.addElement(muscle);
                }
                break;
            case "Dos":
                model.removeAllElements();
                for (String muscle : D) {
                    model.addElement(muscle);
                }
                break;
            case "Pectoraux":
                model.removeAllElements();
                for (String muscle : P) {
                    model.addElement(muscle);
                }
                break;
            case "Epaules":
                model.removeAllElements();
                for (String muscle : E) {
                    model.addElement(muscle);
                }
                break;
        }
    }//GEN-LAST:event_txtGrpMuscuActionPerformed

    //OPtions
    private void bpNewDataBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpNewDataBaseActionPerformed
        // TODO add your handling code here:
        Excel excel = new Excel("BaseDeDonnee");
        excel.creerFichierExcel("BaseDeDonnee");
    }//GEN-LAST:event_bpNewDataBaseActionPerformed

    //Planning
    private void txtNomSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomSeanceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNomSeanceActionPerformed

    private void txtRechercheSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRechercheSeanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechercheSeanceActionPerformed

    private void txtRechercheSeanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRechercheSeanceMouseClicked
        // TODO add your handling code here:
        txtRechercheSeance.setText(null);
    }//GEN-LAST:event_txtRechercheSeanceMouseClicked

    private void bpSupprimerExercice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpSupprimerExercice2ActionPerformed
        // TODO add your handling code here:
        String recherche = txtRechercheSeance.getText();
        int numeroExo = Integer.parseInt(txtRechercheNumeroExercice.getText());
        Seance seance = new Seance("init", "", "");
        int ligne = seance.getLigneSeance(recherche);
        int colonne = numeroExo + 1;
        System.out.println(recherche + numeroExo);
        seance.removeExerciceSeance(recherche, numeroExo);
        
        tableSeance.getModel().setValueAt(null, ligne - 1, colonne);
    }//GEN-LAST:event_bpSupprimerExercice2ActionPerformed

    //Seance
    private void bpSupprimerSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpSupprimerSeanceActionPerformed
        // TODO add your handling code here:
        String recherche = txtRechercheSeance.getText();
        Seance seance = new Seance("init", "", "");
        int ligne = seance.getNombreLigneSeance();

        seance.removeSeance(recherche);
        ligne --;
        for(int i = 0; i <= ligne; i++){
            String[] seanceData = seance.lectureDonneesSeance(i+1);
            for(int c = 0; c <= 11; c++){
                tableSeance.getModel().setValueAt(seanceData[c], i, c);
            }
        }
        DefaultTableModel model = (DefaultTableModel) tableSeance.getModel();
        model.removeRow(ligne);
    }//GEN-LAST:event_bpSupprimerSeanceActionPerformed

    private void txtNomSeance2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomSeance2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bpAjouterSeanceActionPerformed(null);
        }
        
    }//GEN-LAST:event_txtNomSeance2KeyPressed

    private void txtNomSeance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomSeance2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNomSeance2ActionPerformed

    private void txtNomSeance2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomSeance2MouseClicked
        // TODO add your handling code here:
        txtNomSeance2.setText(null);
        Exercice exercice = new Exercice("init","","","");
        int exoMax = exercice.getNombreLigneExercice();
        String[] dataExo = new String[exoMax];
        
        for(int i = 1; i <= exoMax; i++){
            dataExo[i-1] = exercice.getExercice(i);
        }
        
        //Arrays.sort(dataExo); //tri par ordre alphabétique
        Arrays.sort(dataExo, String.CASE_INSENSITIVE_ORDER);
        
        DefaultComboBoxModel model = (DefaultComboBoxModel) txtExercice2.getModel();
        
        model.removeAllElements();
        for (String exerciceData : dataExo) {
            model.addElement(exerciceData);
        } 
    }//GEN-LAST:event_txtNomSeance2MouseClicked

    private void bpAjouterSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpAjouterSeanceActionPerformed
        // TODO add your handling code here:

        int nombreExo = 0; //static ??

        Seance test = new Seance("init","","");
        String type = (String)txtTypeSeance.getSelectedItem();
        String nomSeance = txtNomSeance2.getText();
        String exercice = (String)txtExercice2.getSelectedItem();

        if(test.testNomSeance(nomSeance) == false){
            Seance seance = new Seance(nomSeance, type, exercice);
            DefaultTableModel model = (DefaultTableModel) tableSeance.getModel();
            model.addRow(new Object[]{nomSeance, type, exercice});
            nombreExo++;
            labelNombreExercice.setText(Integer.toString(nombreExo));
        }
        else{
            Seance seance = new Seance("init", "", "");
            seance.setExerciceSeance(nomSeance, exercice);
            
            DefaultTableModel model = (DefaultTableModel) tableSeance.getModel();
            int ligne = test.getLigneSeance(nomSeance);
            int colonne = test.getColonneSeance(ligne);
            tableSeance.getModel().setValueAt(exercice, ligne - 1, colonne - 1);
            /*
            model.removeRow(ligne);
            
            String[] seanceData = seance.lectureDonneesSeance(ligne + 1);//+1
            model.addRow(new Object[]{
                    seanceData[0], seanceData[1], seanceData[2], seanceData[3],
                    seanceData[4], seanceData[5], seanceData[6], seanceData[7],
                    seanceData[8], seanceData[9], seanceData[10], seanceData[11]
                    });
            */
            /*
            for(int c = 0; c <= 11; c++){
                tableSeance.getModel().setValueAt(null, ligne, c);
            }
            String[] seanceData = seance.lectureDonneesSeance(ligne);
            for(int c = 0; c <= 11; c++){
                tableSeance.getModel().setValueAt(seanceData[c], ligne, c);
            }
            
            //tableSeance.getModel().setValueAt(exercice, ligne, colonne);
            
            nombreExo += colonne;
            labelNombreExercice.setText(Integer.toString(nombreExo));
            */
            /*
            model.removeRow(ligne);
            nombreExo += colonne - 2;
            String tabExercices = "";
            for(int i = 1; i < nombreExo; i++){
                tabExercices += " , \" \"" ;
                //nombreExo++;
            }
            nombreExo++;
            tabExercices += exercice;
            model.addRow(new Object[]{nomSeance, type, exercice});
            //labelNombreExercice.setText(Integer.toString(nombreExo));
            */
            
            //Raffaichissement du tableau :
            /*
            int ligneM = seance.getNombreLigneSeance();
            DefaultTableModel model = (DefaultTableModel) tableSeance.getModel();
            for(int l = 0; l <= ligneM; l++){
                model.removeRow(l);
            }
            initialisation();
            */
        }
        
    }//GEN-LAST:event_bpAjouterSeanceActionPerformed

    private void txtExercice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExercice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExercice2ActionPerformed

    private void txtTypeSeanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeSeanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeSeanceActionPerformed

    private void txtRechercheSeanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheSeanceKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bpSupprimerSeanceActionPerformed(null);
        }
    }//GEN-LAST:event_txtRechercheSeanceKeyPressed

    private void txtRechercheNumeroExerciceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRechercheNumeroExerciceMouseClicked
        // TODO add your handling code here:
        txtRechercheNumeroExercice.setText(null);
    }//GEN-LAST:event_txtRechercheNumeroExerciceMouseClicked

    private void txtRechercheNumeroExerciceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRechercheNumeroExerciceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechercheNumeroExerciceActionPerformed

    private void txtRechercheNumeroExerciceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheNumeroExerciceKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bpSupprimerExercice2ActionPerformed(null);
        }
    }//GEN-LAST:event_txtRechercheNumeroExerciceKeyPressed

    //Musculation
    private void txtExercice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExercice3ActionPerformed
        // TODO add your handling code here:
        Musculation muscu = new Musculation("init", "","","");
        String heure = muscu.getHeure();
        String date = muscu.getDate();
        
        txtDate.setText(date);
        txtHeure.setText(heure);
        txtSerie.setText(null);
        txtRepetition.setText(null);
        txtPoids.setText(null);
        
    }//GEN-LAST:event_txtExercice3ActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtHeureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeureActionPerformed

    private void bpAjouterMusculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpAjouterMusculationActionPerformed
        // TODO add your handling code here:
        
        String nomExo = (String)txtExercice3.getSelectedItem();
        String date = txtDate.getText();
        String heure = txtHeure.getText();
        int serie = Integer.parseInt(txtSerie.getText());
        int repetition = Integer.parseInt(txtRepetition.getText());
        int poids = Integer.parseInt(txtPoids.getText());
        
        Musculation muscu = new Musculation("init","","","");
        muscu.updateMusculation(nomExo, heure, date, serie, repetition, poids);
        //int ligne = exercice.getNombreLigneExercice();
        //tableExercice.getModel().addRow(new Object[]{nomExo, typeExo, grpMuscu, muscle});
        DefaultTableModel model = (DefaultTableModel) tableMusculation.getModel();
        model.addRow(new Object[]{nomExo, date, heure, serie, repetition, poids});
        
        /*
        tableExercice.getModel().setValueAt(nomExo, ligne - 1, 0);
        tableExercice.getModel().setValueAt(typeExo, ligne - 1, 1);
        tableExercice.getModel().setValueAt(grpMuscu, ligne - 1, 2);
        tableExercice.getModel().setValueAt(muscle, ligne - 1, 3);
        */
        
        txtDate.setText(null);
        txtHeure.setText(null);
        txtSerie.setText("Séries");
        txtRepetition.setText("Répétitions");
        txtPoids.setText("Poids");
    }//GEN-LAST:event_bpAjouterMusculationActionPerformed

    private void txtPoidsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPoidsKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bpAjouterMusculationActionPerformed(null);
        }
    }//GEN-LAST:event_txtPoidsKeyPressed

    private void txtSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerieActionPerformed

    private void txtRepetitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepetitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepetitionActionPerformed

    private void txtPoidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPoidsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPoidsActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        Exercice exercice = new Exercice("init","","","");
        int exoMax = exercice.getNombreLigneExercice();
        String[] dataExo = new String[exoMax];
        
        for(int i = 1; i <= exoMax; i++){
            dataExo[i-1] = exercice.getExercice(i);
        }
        
        //Arrays.sort(dataExo); //tri par ordre alphabétique
        Arrays.sort(dataExo, String.CASE_INSENSITIVE_ORDER);
        
        DefaultComboBoxModel model = (DefaultComboBoxModel) txtExercice3.getModel();
        
        model.removeAllElements();
        for (String exerciceData : dataExo) {
            model.addElement(exerciceData);
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    //Exercice
    private void txtRechercheExerciceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRechercheExerciceKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            bpSupprimerExerciceActionPerformed(null);
        }
    }//GEN-LAST:event_txtRechercheExerciceKeyPressed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Exercices;
    private javax.swing.JPanel Musculation;
    private javax.swing.JPanel Options;
    private javax.swing.JPanel Planning;
    private javax.swing.JPanel Séances;
    protected javax.swing.JButton bpAjouterExercice;
    protected javax.swing.JButton bpAjouterMusculation;
    protected javax.swing.JButton bpAjouterSeance;
    private javax.swing.JButton bpModifier;
    private javax.swing.JButton bpNewDataBase;
    private javax.swing.JButton bpSupprimer;
    private javax.swing.JButton bpSupprimerExercice;
    protected javax.swing.JButton bpSupprimerExercice2;
    protected javax.swing.JButton bpSupprimerSeance;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelDimanche;
    private javax.swing.JLabel labelDimancheSeance;
    private javax.swing.JLabel labelJeudi;
    private javax.swing.JLabel labelJeudiSeance;
    private javax.swing.JLabel labelLundi;
    private javax.swing.JLabel labelLundiSeance;
    private javax.swing.JLabel labelMardi;
    private javax.swing.JLabel labelMardiSeance;
    private javax.swing.JLabel labelMercredi;
    private javax.swing.JLabel labelMercrediSeance;
    private javax.swing.JLabel labelNombreExercice;
    private javax.swing.JLabel labelSamedi;
    private javax.swing.JLabel labelSamediSeance;
    private javax.swing.JLabel labelVendredi;
    private javax.swing.JLabel labelVendrediSeance;
    public static javax.swing.JTable tableExercice;
    public static javax.swing.JTable tableMusculation;
    public static javax.swing.JTable tableSeance;
    private javax.swing.JFormattedTextField txtDate;
    private javax.swing.JComboBox<String> txtExercice2;
    private javax.swing.JComboBox<String> txtExercice3;
    private javax.swing.JComboBox<String> txtGrpMuscu;
    private javax.swing.JFormattedTextField txtHeure;
    private javax.swing.JComboBox<String> txtJourSeance;
    private javax.swing.JComboBox<String> txtMuscle;
    private javax.swing.JTextField txtNomExercice;
    private javax.swing.JComboBox<String> txtNomSeance;
    private javax.swing.JTextField txtNomSeance2;
    private javax.swing.JTextField txtPoids;
    private javax.swing.JTextField txtRechercheExercice;
    private javax.swing.JTextField txtRechercheNumeroExercice;
    private javax.swing.JTextField txtRechercheSeance;
    private javax.swing.JTextField txtRepetition;
    private javax.swing.JTextField txtSerie;
    private javax.swing.JComboBox<String> txtTypeExercice;
    private javax.swing.JComboBox<String> txtTypeSeance;
    // End of variables declaration//GEN-END:variables
}
